### ISSUE TITLE
How can I get Test Case Body (with Log messages) on HTML Test Overview

### ISSUE THREAD

**Issue by aszegedi** [allure-framework/allure-rspec#84]
Hi,

**Could you help me out in this question? I'm pretty new here. So I'm not sure, may this would be a feature request or I'm just missed a major info somewhere... I'd like to use Test Case `Overview > Test Body` in Allure RSpec HTML report to show the failed test step along with the related test case.**
> Something like that was described here: https://github.com/allure-framework/allure-python/issues/209.

So I'd like to see the failed step within the test case. Unfortunately I was not able to find a related documentation or a Q&A for RSpec Allure Reporter Test Body.

> I found some related questions in case of other languages like at: https://github.com/allure-framework/allure-mocha/issues/38 and https://github.com/allure-framework/allure-java/issues/113

**Comment by smecsia** [comment]
Hi @aszegedi please find the example of steps usage in the readme. Steps allow you to create "sub-tests" that are included into your main test case.

**Comment by aszegedi** [comment]
@smecsia Thank you for your help! I was to be overlooked this part of your README.

I was able to split my test to steps and I can get it on my RSpec Allure HTML. How can I show the whole error (same as console) here? For example:
```
Failures:
  1) Users test cases User - List
     Failure/Error: puts "Hash Actual Response: #{hashActualResponse.sort_by { |_, actual| -actual }}"
     
     NoMethodError:
       undefined method `-@' for nil:NilClass
     # ./spec/common/mock_helper.rb:106:in `block in getResponseDiff'
     # ./spec/common/mock_helper.rb:106:in `each'
     # ./spec/common/mock_helper.rb:106:in `sort_by'
     # ./spec/common/mock_helper.rb:106:in `getResponseDiff'
```
this whole information in my failed step body instead of just:
```
       undefined method `-@' for nil:NilClass
```
Thank you again, for your support on this!
